# Generated by Django 3.2.11 on 2022-01-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_value', models.IntegerField()),
                ('delivery_distance', models.IntegerField()),
                ('number_of_items', models.IntegerField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
